### ISSUE TITLE
Broken link in Readme.md

### ISSUE THREAD

**Issue by phillhocking** [ThoughtWorksStudios/eb_deployer#108]
Just a heads up, I was looking at the Readme.md for eb_deployer and clicked on the "Introduction to EbDeployer" link which is broken to the domain `getmingle.io' with an RST. 

![image](https://user-images.githubusercontent.com/4030898/57579037-22662700-744b-11e9-95ec-27be8b3e0e47.png)

This would have occurred 0700 UTC on 5/12/2019.

**Comment by marques-work** [comment]
Hi there - thanks for letting me know. As Mingle is no more, I'll be sure
to remove this link. Thanks!

**Comment by marques-work** [comment]
Fixed - updated with a direct link.
