### ISSUE TITLE
Solution Stack for Node.js App?

### ISSUE THREAD

**Issue by zbintliff** [ThoughtWorksStudios/eb_deployer#31]
I cant find anything to specific the Node.js app.  I know the default you have is the 64 Bit Linux running Tomcat 7.

How can we deploy Node.js apps through eb_deployer?

**Comment by betarelease** [comment]
Node.js apps also can be packaged as you package a ruby app and deploy(tar.gz). We have not done this before but you would need to ensure yourselves that the 64bit Linux server has all the prerequisites installed as well. 

I suggest looking up available AMIs(there is bound to be one that is node.js ready) and use them. Alternatively if you want to do vanilla node.js look at Amazon's Lambda service. 

Sudhindra.
