### ISSUE TITLE
Unitialized constant error

### ISSUE THREAD

**Issue by dermdunc** [ThoughtWorksStudios/eb_deployer#33]
Wondering if I'm missing something obvious but seeing the following error when running step 4 from the readme

Found configuration at config/eb_deployer.yml.
/usr/local/lib/ruby/gems/2.1.0/gems/eb_deployer-0.4.9/lib/eb_deployer/config_loader.rb:50:in `load_config_settings': uninitialized constant EbDeployer::ConfigLoader::YAML (NameError)

Anyone else come across this or any ideas what I might be doing wrong?

**Comment by dermdunc** [comment]
This looks to only be an issue on OSX, on linux machines it seems to run fine.

**Comment by betarelease** [comment]
Looks like your rubygems is on 2.1.0 - seems pretty old. Can you please try
an upgrade of rubygems itself on osx and rerun. We use mac osx for
development and have not seen this before.

Thanks,
Sudhindra.

On Tue, Jan 27, 2015 at 10:05 PM, Derm <notifications@github.com> wrote:

> This looks to only be an issue on OSX, on linux machines it seems to run
> fine.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ThoughtWorksStudios/eb_deployer/issues/33#issuecomment-71785879>
> .
>



-- 
Sudhindra.
@sudhindraRao

**Comment by dermdunc** [comment]
The same issue just started appearing on a linux machine which was previously working... I tried updating ruby but seeing the same behavior

Found configuration at config/eb_deployer.yml.
/home/rof/.rvm/gems/ruby-2.2.0/gems/eb_deployer-0.4.9/lib/eb_deployer/config_loader.rb:50:in `load_config_settings': uninitialized constant EbDeployer::ConfigLoader::YAML

**Comment by Blackbaud-FrankMata** [comment]
I am also seeing the issue on the latest Amazon Linux as well, it just started today. I think this is a problem with the aws-sdk version. They released a new gem today:

https://rubygems.org/gems/aws-sdk/versions

2.0.22 - February 5, 2015 (4.5 KB)

Changed the gem requirement in 
https://github.com/ThoughtWorksStudios/eb_deployer/blob/master/eb_deployer.gemspec

to "1.61.0" from ">= 1.33.0" and it is now working.

**Comment by xli** [comment]
@Blackbaud-FrankMata @dermdunc I just pushed out a fix for this problem, could you try upgrade to latest version 0.4.10 and confirm the fix works for you?

**Comment by dermdunc** [comment]
Thanks xli but I'm seeing a similar issue with the latest version on Amazon Linux... It could be down to the latest aws-sdk or the order of the requires.

/home/rof/.rvm/gems/ruby-2.2.0/gems/eb_deployer-0.4.10/lib/eb_deployer.rb:174:in `deploy': uninitialized constant EbDeployer::AWS (NameError)
	from /home/rof/.rvm/gems/ruby-2.2.0/gems/eb_deployer-0.4.10/lib/eb_deployer.rb:255:in `cli'
	from /home/rof/.rvm/gems/ruby-2.2.0/gems/eb_deployer-0.4.10/bin/eb_deploy:11:in `<top (required)>'
	from /home/rof/.rvm/gems/ruby-2.2.0/bin/eb_deploy:23:in `load'
	from /home/rof/.rvm/gems/ruby-2.2.0/bin/eb_deploy:23:in `<main>'
	from /home/rof/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `eval'
	from /home/rof/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `<main>

**Comment by xli** [comment]
@dermdunc I didn't realize aws-sdk for ruby 2 has totally changed their api, so I changed eb_deployer to depend on aws-sdk-v1 for now, and pushed out a new version.

**Comment by dermdunc** [comment]
That looks to have cleared the problem - thanks xli.
