### ISSUE TITLE
Deploying the code base to both WebServer and Worker tiers

### ISSUE THREAD

**Issue by willclark** [ThoughtWorksStudios/eb_deployer#34]
Eventually we will split the application up into services. But for time being, is there a recommended way to deploy to both a WebServer and Worker tier?

**Comment by betarelease** [comment]
We do not yet have a combined way to do both at the same time. We have different pipelines or independent jobs for these deployments on gocd. Is there a reason you would want them to be synchronized - is it because you changed a job publisher and processor protocol?

**Comment by wpc** [comment]
We have a component feature we have used for long time but haven't got time to document. Basically you can have a "components" section in the config file to define multiple components in your system such as web cluster, api cluster, background processing cluster. And each component can overrides the global setting individually.

When you deploy ebdeployer will sequentially deploy all the components. You can also deploy a specific component by --component with component name. You can parallel the deployment by deploy multiple components at same time.

There is a example in the codebase. https://github.com/ThoughtWorksStudios/eb_deployer/tree/master/samples/multi_components

Let me know if you encounter any problems.

-- wpc

**Comment by willclark** [comment]
I'll definitely checkout that out, Thanks!

- Will
