### ISSUE TITLE
Support for custom domain

### ISSUE THREAD

**Issue by brotbert** [ThoughtWorksStudios/eb_deployer#37]
Hi,

will be there support for custom domain for swapping environments? (i.e. swap of custom Route53 domain records)

Thanks,
Robert

**Comment by xli** [comment]
Why do you need swap custom Route53 domain records? Could be more specific about the use case so that we understand the problem.

**Comment by brotbert** [comment]
Possible use-cases:

* Independent naming scheme in a hosted zone and not relying on the environment driven names.
* Hiding *.elasticbeanstalk.com away from public (and using ALIAS-Records to the ELB instead)

We're using CNAMEs now as a workaround.

**Comment by xli** [comment]
We use CNAME. It's simple, flexible. Ed_deployer is designed for you to do this.

Don't understand "why and what is independent naming scheme in a hosted zone"

**Comment by brotbert** [comment]
I agree that the first use-case is non-sense since ElasticBeanstalk doesn't support custom domains (other than `elasticbeanstalk.com`) in environments. And I suppose the second isn't one a stopper for anyone either. So I will close this issue.
