### ISSUE TITLE
block in with_polling_events

### ISSUE THREAD

**Issue by itspolo** [ThoughtWorksStudios/eb_deployer#38]
I started getting these errors, a subsequent build fixes it, just wondering if you have insight why this may be occurring.
thanks!

/usr/local/rvm/gems/ruby-2.0.0-p598@bamazon/gems/eb_deployer-0.4.9/lib/eb_deployer/eb_environment.rb:100:in `block in with_polling_events': Elasticbeanstalk instance provision failed (maybe a problem with your .ebextension files). The original message: [Instance: i-281ca0d5] Command failed on instance. An unexpected error has occurred [ErrorCode: 0000000001]. (RuntimeError)
	from /usr/local/rvm/gems/ruby-2.0.0-p598@bamazon/gems/eb_deployer-0.4.9/lib/eb_deployer/event_poller.rb:33:in `block (3 levels) in poll'
	from /usr/local/rvm/gems/ruby-2.0.0-p598@bamazon/gems/eb_deployer-0.4.9/lib/eb_deployer/event_poller.rb:32:in `each'
	from /usr/local/rvm/gems/ruby-2.0.0-p598@bamazon/gems/eb_deployer-0.4.9/lib/eb_deployer/event_poller.rb:32:in `block (2 levels) in poll'
	from /usr/local/rvm/gems/ruby-2.0.0-p598@bamazon/gems/eb_deployer-0.4.9/lib/eb_deployer/event_poller.rb:56:in `fetch_events'
	from /usr/local/rvm/gems/ruby-2.0.0-p598@bamazon/gems/eb_deployer-0.4.9/lib/eb_deployer/event_poller.rb:17:in `block in poll'
	from /usr/local/rvm/gems/ruby-2.0.0-p598@bamazon/gems/eb_deployer-0.4.9/lib/eb_deployer/event_poller.rb:16:in `loop'
	from /usr/local/rvm/gems/ruby-2.0.0-p598@bamazon/gems/eb_deployer-0.4.9/lib/eb_deployer/event_poller.rb:16:in `poll'
	from /usr/local/rvm/gems/ruby-2.0.0-p598@bamazon/gems/eb_deployer-0.4.9/lib/eb_deployer/eb_environment.rb:94:in `with_polling_events'
	from /usr/local/rvm/gems/ruby-2.0.0-p598@bamazon/gems/eb_deployer-0.4.9/lib/eb_deployer/eb_environment.rb:76:in `update_eb_env'
	from /usr/local/rvm/gems/ruby-2.0.0-p598@bamazon/gems/eb_deployer-0.4.9/lib/eb_deployer/eb_environment.rb:25:in `deploy'
	from /usr/local/rvm/gems/ruby-2.0.0-p598@bamazon/gems/eb_deployer-0.4.9/lib/eb_deployer/deployment_strategy/blue_green.rb:18:in `deploy'
	from /usr/local/rvm/gems/ruby-2.0.0-p598@bamazon/gems/eb_deployer-0.4.9/lib/eb_deployer/default_component.rb:16:in `deploy'
	from /usr/local/rvm/gems/ruby-2.0.0-p598@bamazon/gems/eb_deployer-0.4.9/lib/eb_deployer/environment.rb:32:in `block in deploy'
	from /usr/local/rvm/gems/ruby-2.0.0-p598@bamazon/gems/eb_deployer-0.4.9/lib/eb_deployer/environment.rb:31:in `each'
	from /usr/local/rvm/gems/ruby-2.0.0-p598@bamazon/gems/eb_deployer-0.4.9/lib/eb_deployer/environment.rb:31:in `deploy'
	from /usr/local/rvm/gems/ruby-2.0.0-p598@bamazon/gems/eb_deployer-0.4.9/lib/eb_deployer.rb:212:in `deploy'
	from /usr/local/rvm/gems/ruby-2.0.0-p598@bamazon/gems/eb_deployer-0.4.9/lib/eb_deployer.rb:255:in `cli'
	from /usr/local/rvm/gems/ruby-2.0.0-p598@bamazon/gems/eb_deployer-0.4.9/bin/eb_deploy:11:in `<top (required)>'
	from /usr/local/rvm/gems/ruby-2.0.0-p598@bamazon/bin/eb_deploy:23:in `load'
	from /usr/local/rvm/gems/ruby-2.0.0-p598@bamazon/bin/eb_deploy:23:in `<main>'
	from /usr/local/rvm/gems/ruby-2.0.0-p598@bamazon/bin/ruby_executable_hooks:15:in `eval'
	from /usr/local/rvm/gems/ruby-2.0.0-p598@bamazon/bin/ruby_executable_hooks:15:in `<main>'

**Comment by betarelease** [comment]
Hi Paolo,
It suggests "Elasticbeanstalk instance provision failed (maybe a problem
with your .ebextension files". Have you been able to deploy with the
current .ebextension files before? If not maybe take another look at what
they contain.

Some examples on what they should contain
https://github.com/lapygithub/eb_config_examples.

Let us know if you are still not able to get this working.

Thanks,
Sudhindra.

On Tue, Apr 14, 2015 at 10:24 AM, Paolo Vaca <notifications@github.com>
wrote:

> I started getting these errors, a subsequent build fixes it, just
> wondering if you have insight why this may be occurring.
> thanks!
>
> /usr/local/rvm/gems/ruby-2.0.0-p598@bamazon
> /gems/eb_deployer-0.4.9/lib/eb_deployer/eb_environment.rb[image: :100:]in block
> in with_polling_events': Elasticbeanstalk instance provision failed (maybe
> a problem with your .ebextension files). The original message: [Instance:
> i-281ca0d5] Command failed on instance. An unexpected error has occurred
> [ErrorCode: 0000000001]. (RuntimeError)
> from /usr/local/rvm/gems/ruby-2.0.0-p598@bamazon
> /gems/eb_deployer-0.4.9/lib/eb_deployer/event_poller.rb:33:inblock (3
> levels) in poll'
> from /usr/local/rvm/gems/ruby-2.0.0-p598@bamazon/gems/eb_deployer-0.4.9/lib/eb_deployer/event_poller.rb:32:in
> each'
> from /usr/local/rvm/gems/ruby-2.0.0-p598@bamazon
> /gems/eb_deployer-0.4.9/lib/eb_deployer/event_poller.rb:32:inblock (2
> levels) in poll'
> from /usr/local/rvm/gems/ruby-2.0.0-p598@bamazon/gems/eb_deployer-0.4.9/lib/eb_deployer/event_poller.rb:56:in
> fetch_events'
> from /usr/local/rvm/gems/ruby-2.0.0-p598@bamazon
> /gems/eb_deployer-0.4.9/lib/eb_deployer/event_poller.rb:17:inblock in
> poll'
> from /usr/local/rvm/gems/ruby-2.0.0-p598@bamazon/gems/eb_deployer-0.4.9/lib/eb_deployer/event_poller.rb:16:in
> loop'
> from /usr/local/rvm/gems/ruby-2.0.0-p598@bamazon
> /gems/eb_deployer-0.4.9/lib/eb_deployer/event_poller.rb:16:inpoll'
> from /usr/local/rvm/gems/ruby-2.0.0-p598@bamazon/gems/eb_deployer-0.4.9/lib/eb_deployer/eb_environment.rb:94:in
> with_polling_events'
> from /usr/local/rvm/gems/ruby-2.0.0-p598@bamazon
> /gems/eb_deployer-0.4.9/lib/eb_deployer/eb_environment.rb:76:in
> update_eb_env'
> from /usr/local/rvm/gems/ruby-2.0.0-p598@bamazon/gems/eb_deployer-0.4.9/lib/eb_deployer/eb_environment.rb:25:in
> deploy'
> from /usr/local/rvm/gems/ruby-2.0.0-p598@bamazon
> /gems/eb_deployer-0.4.9/lib/eb_deployer/deployment_strategy/blue_green.rb:18:in
> deploy'
> from /usr/local/rvm/gems/ruby-2.0.0-p598@bamazon/gems/eb_deployer-0.4.9/lib/eb_deployer/default_component.rb:16:in
> deploy'
> from /usr/local/rvm/gems/ruby-2.0.0-p598@bamazon
> /gems/eb_deployer-0.4.9/lib/eb_deployer/environment.rb:32:inblock in
> deploy'
> from /usr/local/rvm/gems/ruby-2.0.0-p598@bamazon/gems/eb_deployer-0.4.9/lib/eb_deployer/environment.rb:31:in
> each'
> from /usr/local/rvm/gems/ruby-2.0.0-p598@bamazon
> /gems/eb_deployer-0.4.9/lib/eb_deployer/environment.rb:31:indeploy'
> from /usr/local/rvm/gems/ruby-2.0.0-p598@bamazon/gems/eb_deployer-0.4.9/lib/eb_deployer.rb:212:in
> deploy'
> from /usr/local/rvm/gems/ruby-2.0.0-p598@bamazon
> /gems/eb_deployer-0.4.9/lib/eb_deployer.rb:255:incli'
> from /usr/local/rvm/gems/ruby-2.0.0-p598@bamazon/gems/eb_deployer-0.4.9/bin/eb_deploy:11:in
> <top (required)>'
> from /usr/local/rvm/gems/ruby-2.0.0-p598@bamazon/bin/eb_deploy:23:inload'
> from /usr/local/rvm/gems/ruby-2.0.0-p598@bamazon/bin/eb_deploy:23:in
> <main>'
> from /usr/local/rvm/gems/ruby-2.0.0-p598@bamazon
> /bin/ruby_executable_hooks:15:ineval'
> from /usr/local/rvm/gems/ruby-2.0.0-p598@bamazon/bin/ruby_executable_hooks:15:in
> `'
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ThoughtWorksStudios/eb_deployer/issues/38>.
>



-- 
Sudhindra.
@sudhindraRao

**Comment by calebolin** [comment]
Thanks for the reply, Subhindra. Yes, we have been able to deploy with our current .ebextension files. We've opened a ticket with AWS.

It could be unrelated, but we've seen the following in the system logs for instances that have experienced this problem. 

```
udevd[1180]: failed to execute '/lib/udev/input_id' 'input_id /devices/platform/i8042/serio0/input/input0': No such file or directory

udevd[1270]: failed to execute '/lib/udev/input_id' 'input_id /devices/virtual/input/mice': No such file or directory

growroot: NOCHANGE: disk=/dev/xvda partition=1: size=16773086, it cannot be grown
```

Caleb 
(I work with Paolo)

**Comment by calebolin** [comment]
We heard back from AWS:

"It seems that there is currently a timing issue that occurs when a rolling deployment takes place alongside an auto scaling "scale up" event. 

In some cases the additional instance(s) are receiving deployment commands out of sequence. The result is the additional instances may or may not come up running the latest version. We are working on a fix, but this may take some time to properly correct.

There are two workarounds that we can suggest until we fix this issue: 

1. You previously mentioned that you are using a blue/green deployment model. We would like to ask that you continue using blue/green deployments to update your application as this issue should not arise when using the following deployment procedure: 

-Create a clone environment, 
-Deploy the new version of the software to the new environment, 
-Test the application to ensure proper functionality
-Perform a CNAME swap to move the traffic over. 

When you use your blue/green deployment strategy described above do you still experience this error?

2. If wish to use an in-place version update model, then you should turn off auto scaling scale ups 
via the auto scaling console or CLI, perform the rolling update and then turn scale ups back on."
