### ISSUE TITLE
Need clarification regarding the resources section

### ISSUE THREAD

**Issue by behrangsa** [ThoughtWorksStudios/eb_deployer#49]
Hi,

In your [blog post](http://www.thoughtworks.com/mingle/scaling/2014/06/13/introduction-to-eb-deployer.html), you mention that:

> “resources” section defines permanent resources provisioned by CloudFormation.

I am trying to use this to create a DynamoDB table that should be permanent and not recreated after every deployment and blue-green switch.

My CloudFormation template looks like this:

```json
{
    "AWSTemplateFormatVersion": "2010-09-09",
    "Resources": {
        "MyTable": {
            "Type": "AWS::DynamoDB::Table",
            "Properties": {
                "TableName": "my-table-name",
                "AttributeDefinitions": [
                    {
                        "AttributeName": "myId",
                        "AttributeType": "N"
                    }
                ],
                "KeySchema": [
                    {
                        "AttributeName": "myId",
                        "KeyType": "HASH"
                    }
                ],
                "ProvisionedThroughput": {
                    "ReadCapacityUnits": "1",
                    "WriteCapacityUnits": "1"
                }
            }
        }
    }
}

```

And I am referencing it from my `eb_deployer.yaml` file like this:

```yaml
resources:
    template: config/my_dynamo.json
```

When the app is deployed for the first time, it creates the DynamoDB template as expected. However on subsequent runs, the CloudFormation stack creation fails with this error:

```
Status: CREATE_FAILED
Type: AWS::DynamoDB::Table
Logical ID: MyTable
Status Reason: my-table-name already exists in stack arn:aws:cloudformation:...:stack/app-name-production-...-resources/...`
```

Is this a bug? Any ideas what am I missing here? How can we prevent this from happening and create the database once and never recreate it in subsequent deployments?

Thanks.

**Comment by marano** [comment]
Hi @behrangsa!

It seems you may be facing an error specific to how DynamoDB works. EbDeployer will simply try to update the resource with de specified JSON, and AWS handles if any update should actually occur given configuration changes.

From their documentation:
> **Important**
> If you specify a name, you cannot do updates that require this resource to be replaced. You can still do updates that require no or some interruption. If you must replace the resource, specify a new name.

Do you think it might be the case that you changed the configuration from your first ran, and now it needs to recreate the table?

**Comment by behrangsa** [comment]
Hi @marano,

Not really. I deployed my app once it worked with no problem. Then I redeployed the same app with no changes and it faced the shown error.

I just have to mention that I'm using the blue-green strategy.

Cheers,
Behrang

**Comment by marano** [comment]
Hey @behrangsa, would you mind going to the AWS console and try to update the cloud formation stack? You may keep the same template and values for all fields, just use the default options and click next until its done. This is supposed to be a simulation of what EbDeployer is doing, if these steps work then we can try narrowing the issue on EbDeployer, otherwise you might need to fix the template.

**Comment by behrangsa** [comment]
@marano, looks like the problem is with the JS fork of eb_deployer we are using: https://github.com/bernos/eb-deployer-js

I tried the original Ruby version (this repo), and it works with no problem.

With the Ruby version, the stack created via resources has a name like `my-stack`. With our version, with each deployment it gets a random number appended to it `my-stack-123`. So for each deployment, eb_deployer tries to create a new stack for the same DynamoDB table which fails, because the table already exists and belongs to another stack.

Thanks for your help. I think I can now close this issue.
