### ISSUE TITLE
Access environment name in CloudFormation template

### ISSUE THREAD

**Issue by willclark** [ThoughtWorksStudios/eb_deployer#50]
I'd like to be able to append the environment to the end of SQS queue and DynamoDB table names. For instance, StackNameQueue-production.

Any advice on accomplishing this?

Thanks,
Will

**Comment by xli** [comment]
Hi @willclark 
Just added an environment variable for eb_deployer.yml file to substitute.
EbDeployer will load eb_deployer.yml file as ERB template, so you can do something like this to your eb_deployer.yml file :
----------
  resources:
    inputs:
      env: <%= environment %>
----------
Then, add a new parameter to your CloudFormation template file:
        "env": {
            "Description": "deploy environment name",
            "Type": "String"
        },
---------
Then use the parameter in your template for your SQS queue and DynamoDB table name.

**Comment by willclark** [comment]
Awesome. Thank you!
