### ISSUE TITLE
How to "rollback" a blue-green deployment

### ISSUE THREAD

**Issue by nicolai86** [ThoughtWorksStudios/eb_deployer#54]
Using the `blue-green` deployment mode, how do I use `eb_deploy` to re-activate the old environment, without deploying? Is this implemented yet?

**Comment by wpc** [comment]
eb_deployer creates two Elastic Beanstalk environment for you under the application name specified. One of them has active url looks like: my-app-production.elasticbeanstalk.com, the other one has inactive url like my-app-production-inactive.elasticbeanstalk.com. The deployment always happens to env with inactive url, then eb_deployer swaps it's url with active environment. 

If you find problem in what just deployed,  you can "rollback" the deployment by swapping the url back. To do this login into Elastic Beanstalk AWS management console, open one of the two environments eb_deployer created, click "Actions -> Swap Environment URLs", and swap it with the other environment.

![EB AWS Management Console Swap URLs](http://docs.aws.amazon.com/elasticbeanstalk/latest/dg/images/aeb-env-dashboard-swapurls.png)

**Comment by nicolai86** [comment]
Thanks for the response. I was hoping for a way to not use the AWS gui, but changing the smoketest makes perfect sense. Thanks a lot!

**Comment by wpc** [comment]
Hi, @nicolai86:
I find myself normally prefer manual solution with transparency when sh*t happens. But even thats said it is still valuable to implement "rollback" in eb_deployer. To make the flow complete and give user choices. I will put it into the roadmap. (And open for pull request :-)) Thank you for your suggestion.
