### ISSUE TITLE
Need an easy way to create a specific ELB Security Group.

### ISSUE THREAD

**Issue by bryantidd** [ThoughtWorksStudios/eb_deployer#60]
Need an easy way to create and specify a ELB Security Group. The auto generated one from Elastic Beanstalk is inappropriate.

**Comment by xli** [comment]
@bryantidd, you can create one by cloudformation, then output it to eb_deployer.yml config file, example:

    resources:
      template: config/aws_resources.json
      capabilities:
        - CAPABILITY_IAM
      inputs:
        Namespace: <%= environment %>
      outputs:
        SecurityGroupName:
          namespace: aws:autoscaling:launchconfiguration
          option_name: SecurityGroups

In aws_resources.json CloudFormation template file, you create a new security group:

        "MySecurityGroup" : {
            "Type" : "AWS::EC2::SecurityGroup",
            "Properties" : {
                "GroupDescription" : "MongoDB security group",
                "SecurityGroupIngress" : [
                    {
                        "IpProtocol" : "tcp",
                        "FromPort" : "22",
                        "ToPort" : "22",
                        "CidrIp" : "0.0.0.0/0"
                    }
                ]
            }
        },

Then output it:

    "Outputs" : {
        "SecurityGroupName" : {
            "Value" : { "Ref" : "MySecurityGroup" },
            "Description" : "Security group name of MongoInstance"
        },
    }

**Comment by bryantidd** [comment]
Yes, actually, I was hoping to force it to use just that security group, and not automatically create one with 80 open to the world. I have read that that is not currently possible. Maybe I am wrong. The way you suggested is the way I was doing it, but it only adds that group to the automatically created one. Especially as relates to the ELB security group.

**Comment by xli** [comment]
I don't understand what you mean of 80 open will be opened to the world.
You should create mongodb server with CloudFormation, not ElasticBeanstalk.

You application deployed to ElasticBeanstalk will open 80 port when it is a web tier, if you're doing background job, do not need 80 port, you should consider worker tier.

If worker tier does not match your need, then you should consider other way to deploy your app.

I used a web tier for background job stuff too.
With 80 port open, it is easier for me to write a simple stuff for monitoring purpose.

**Comment by bryantidd** [comment]
Well, In this case it is a web application, but I want to white list a specific CIDR and ports that can access it. Not open to the world at large. Primarily because AWS IPs are scanned all the time by bots, and I don't want anyone but Mashery IPs to be able to access it. So Explain how worker is different.....

**Comment by xli** [comment]
@bryantidd As I know, worker tire does not have ELB, you should have full control of how you want to access the instance. 
 You need check their document and try it out.
