### ISSUE TITLE
Feature: Make Yellow an accepted current_health_status

### ISSUE THREAD

**Issue by dziemid** [ThoughtWorksStudios/eb_deployer#66]
Hello,

We have a use case where we would like to treat "Yellow" Elastic Beanstalk environment health status as healthy. 

"Yellow" state occurs for us in a worker  environment when there is a lot of messages in the queue waiting to be consumed. This happens quite a lot for us due to a nature of our workload. 

At the moment, this is hardcoded to "Green" here:
https://github.com/ThoughtWorksStudios/eb_deployer/blob/master/lib/eb_deployer/eb_environment.rb#L166

Would it be possible to make EB Deployer configurable, so that it can accept "Yellow" as an healthy state? If so, we are happy to make a pull request.

**Comment by xli** [comment]
Please send a pull request

**Comment by wpc** [comment]
@dziemid thank you for your contribution, 0.6.5 released includes the change.
