### ISSUE TITLE
blue/green deploy

### ISSUE THREAD

**Issue by dcho2013** [ThoughtWorksStudios/eb_deployer#68]
I'm trying to do a blue/green deploy but only in-place update is occurring.
AWS Beanstalk DNS names have changed to include a region, for example:
mysite.us-east-1.elasticbeanstalk.com

Is the new domain name structure affecting this or do I need to explicitly state blue green strategy in my YAML?

**Comment by dcho2013** [comment]
Nevermind I figured out my error.

Thanks

**Comment by darkoz** [comment]
@dcho2013 what was the error? I have a similar issue.
