### ISSUE TITLE
Using Latest Versions of Passenger - how to do?

### ISSUE THREAD

**Issue by dashbitla** [ThoughtWorksStudios/eb_deployer#72]
Right now Beanstalk comes with 4.x version of Passenger as an environment.
There are ton of advanced features with 5.x version of Passenger.
Is there any ways we can use latest version of Passenger with Nginx? Or Enterprise Passenger version??

**Comment by xli** [comment]
Change solution stack name (in config file eb_deployer.yml) to what you like to use:
  # Solution stack for elastic beanstalk, default is 64bit tomcat 7 for JAVA app
  # solution_stack_name: 64bit Amazon Linux 2014.03 v1.0.3 running Tomcat 7 Java 7
