### ISSUE TITLE
Deploying using different Default AWS Profile?

### ISSUE THREAD

**Issue by jonmchan** [ThoughtWorksStudios/eb_deployer#73]
In eb, you can switch profiles using the ```--profile``` option to change the credentials that you are using. Is this option exposed to ```eb_deployer```?

**Comment by xli** [comment]
@jonmchan, eb_deployer depends on environment variables to setup credentials:

      $ export AWS_ACCESS_KEY_ID=xxx
      $ export AWS_SECRET_ACCESS_KEY=xxx

So, there is no --profile option

**Comment by digitalfiz** [comment]
It would be nice if it respected AWS_DEFAULT_PROFILE so that we didn't have to specify the key/secret or modify our .aws/config when we wanted to use it.
