### ISSUE TITLE
hold off on blue/green cname swap

### ISSUE THREAD

**Issue by ap-dji** [ThoughtWorksStudios/eb_deployer#76]
I'm working on setting up a deployment pipeline and I would like to hold off on the final cname swap so I can run more tests in a separate pipeline step before doing the switch.  Is there any built-in way to do this now?  Anyone doing anything similar?

**Comment by xli** [comment]
@ap-dji if that's the case, you don't need eb_deployer, use tool or sdk provided by AWS  is enough.

**Comment by ap-dji** [comment]
@xli Actually it looks like the existing blue-only strategy is what I was looking for, but I'll just have to use the cli or sdk, as you suggested, to do the swap at a later time.
