### ISSUE TITLE
Grails deployment

### ISSUE THREAD

**Issue by kkoci** [ThoughtWorksStudios/eb_deployer#80]
Hi ,

Can I use eb_deployer, to deploy .war groovy files to Beanstalk?

Is it language agnostic? Or it needs to be a Rails project?

Thanks in advance!

**Comment by wpc** [comment]
It is language agnostic. eb_deployer support any platform elasticbeanstalk supports. To elasticbeanstalk your groovy war is nothing different with a normal java webapp.

**Comment by kkoci** [comment]
Thank You very much wpc
